export type WorkbenchRecordType = "oa" | "bank" | "invoice";

export type WorkbenchActionVariant = "detail-only" | "bank-review" | "confirm-exception";

export type WorkbenchDetailField = {
  label: string;
  value: string;
};

export type WorkbenchRecord = {
  id: string;
  caseId?: string;
  recordType: WorkbenchRecordType;
  label: string;
  status: string;
  amount: string;
  counterparty: string;
  tableValues: Record<string, string>;
  detailFields: WorkbenchDetailField[];
  actionVariant: WorkbenchActionVariant;
};

export const pairedRecords = {
  oa: [
    {
      id: "OA-202603-001",
      caseId: "CASE-202603-001",
      recordType: "oa",
      label: "付款申请",
      status: "完全关联",
      amount: "128,000.00",
      counterparty: "华东设备供应商",
      actionVariant: "detail-only",
      tableValues: {
        applicant: "赵华",
        projectName: "华东改造项目",
        applicationType: "供应商付款申请",
        amount: "128,000.00",
        counterparty: "华东设备供应商",
        reason: "设备首付款支付",
        reconciliationStatus: "完全关联",
      },
      detailFields: [
        { label: "OA单号", value: "OA-202603-001" },
        { label: "审批完成时间", value: "2026-03-25 11:05" },
        { label: "当前流程", value: "财务复核完成" },
        { label: "创建部门", value: "华东交付部" },
      ],
    },
    {
      id: "OA-202603-002",
      caseId: "CASE-202603-002",
      recordType: "oa",
      label: "报销单",
      status: "正常关联",
      amount: "860.00",
      counterparty: "差旅报销",
      actionVariant: "detail-only",
      tableValues: {
        applicant: "刘宁",
        projectName: "智能工厂项目",
        applicationType: "差旅报销",
        amount: "860.00",
        counterparty: "差旅报销",
        reason: "现场实施差旅费",
        reconciliationStatus: "正常关联",
      },
      detailFields: [
        { label: "OA单号", value: "OA-202603-002" },
        { label: "审批完成时间", value: "2026-03-24 17:20" },
        { label: "当前流程", value: "自动闭环" },
        { label: "创建部门", value: "实施交付部" },
      ],
    },
  ] satisfies WorkbenchRecord[],
  bank: [
    {
      id: "BNK-202603-101",
      caseId: "CASE-202603-001",
      recordType: "bank",
      label: "支取",
      status: "完全关联",
      amount: "128,000.00",
      counterparty: "华东设备供应商",
      actionVariant: "bank-review",
      tableValues: {
        transactionTime: "2026-03-25 14:22",
        debitAmount: "128,000.00",
        creditAmount: "--",
        counterparty: "华东设备供应商",
        paymentAccount: "招商银行 9123",
        invoiceRelationStatus: "完全关联",
        paymentOrReceiptTime: "2026-03-25 14:22",
        note: "设备采购款，已闭环",
        loanRepaymentDate: "--",
      },
      detailFields: [
        { label: "账号", value: "6225 **** **** 9123" },
        { label: "账户名称", value: "溯源科技有限公司-招商银行基本户" },
        { label: "余额", value: "2,488,310.55" },
        { label: "币种", value: "CNY" },
        { label: "对方账号", value: "6214 **** **** 4432" },
        { label: "对方开户机构", value: "中国银行上海张江支行" },
        { label: "记账日期", value: "2026-03-25" },
        { label: "摘要", value: "设备供应商付款" },
        { label: "备注", value: "OA 已闭环，进项票已核销" },
        { label: "账户明细编号-交易流水号", value: "DET-20260325-101" },
        { label: "企业流水号", value: "CORP-20260325-7781" },
        { label: "凭证种类", value: "网银付款" },
        { label: "凭证号", value: "VCH-031525-01" },
      ],
    },
    {
      id: "BNK-202603-102",
      caseId: "CASE-202603-002",
      recordType: "bank",
      label: "支取",
      status: "正常关联 - 内部往来",
      amount: "860.00",
      counterparty: "集团共享账户",
      actionVariant: "bank-review",
      tableValues: {
        transactionTime: "2026-03-24 10:05",
        debitAmount: "860.00",
        creditAmount: "--",
        counterparty: "集团共享账户",
        paymentAccount: "建设银行 1138",
        invoiceRelationStatus: "正常关联 - 内部往来",
        paymentOrReceiptTime: "2026-03-24 10:05",
        note: "内部调拨已回填往来银行",
        loanRepaymentDate: "--",
      },
      detailFields: [
        { label: "账号", value: "6217 **** **** 1138" },
        { label: "账户名称", value: "溯源科技有限公司-建设银行一般户" },
        { label: "余额", value: "581,203.18" },
        { label: "币种", value: "CNY" },
        { label: "对方账号", value: "6217 **** **** 0048" },
        { label: "对方开户机构", value: "建设银行北京分行营业部" },
        { label: "记账日期", value: "2026-03-24" },
        { label: "摘要", value: "内部往来调拨" },
        { label: "备注", value: "内部往来款记录已自动回填" },
        { label: "账户明细编号-交易流水号", value: "DET-20260324-102" },
        { label: "企业流水号", value: "CORP-20260324-0846" },
        { label: "凭证种类", value: "转账支取" },
        { label: "凭证号", value: "VCH-032410-02" },
      ],
    },
  ] satisfies WorkbenchRecord[],
  invoice: [
    {
      id: "INV-OUT-202603-001",
      caseId: "CASE-202603-001",
      recordType: "invoice",
      label: "销项票",
      status: "已核销",
      amount: "128,000.00",
      counterparty: "华东项目甲方",
      actionVariant: "detail-only",
      tableValues: {
        sellerTaxId: "91310000MA1K8A001X",
        sellerName: "溯源科技有限公司",
        buyerTaxId: "91310110MA1F99088Q",
        buyerName: "华东项目甲方",
        issueDate: "2026-03-25",
        amount: "128,000.00",
        taxRate: "13%",
        taxAmount: "16,640.00",
        grossAmount: "144,640.00",
        invoiceType: "数电专票",
      },
      detailFields: [
        { label: "序号", value: "1" },
        { label: "发票代码", value: "032002600111" },
        { label: "发票号码", value: "00061345" },
        { label: "数电发票号码", value: "DZFP-202603-9001" },
        { label: "税收分类编码", value: "3040201000000000000" },
        { label: "特定业务类型", value: "设备集成" },
        { label: "货物或应税劳务名称", value: "工业控制设备" },
        { label: "规格型号", value: "ICD-2000" },
        { label: "单位", value: "套" },
        { label: "数量", value: "1" },
        { label: "单价", value: "128,000.00" },
        { label: "发票来源", value: "税局数电" },
        { label: "发票票种", value: "增值税电子专用发票" },
        { label: "发票状态", value: "正常" },
        { label: "是否正数发票", value: "是" },
        { label: "发票风险等级", value: "低" },
        { label: "开票人", value: "王青" },
        { label: "备注", value: "已与银行收款和 OA 闭环" },
      ],
    },
    {
      id: "INV-IN-202603-011",
      caseId: "CASE-202603-002",
      recordType: "invoice",
      label: "进项票",
      status: "已核销",
      amount: "860.00",
      counterparty: "差旅服务商",
      actionVariant: "detail-only",
      tableValues: {
        sellerTaxId: "91310108MA1N22179P",
        sellerName: "差旅服务商",
        buyerTaxId: "91310000MA1K8A001X",
        buyerName: "溯源科技有限公司",
        issueDate: "2026-03-24",
        amount: "860.00",
        taxRate: "6%",
        taxAmount: "51.60",
        grossAmount: "911.60",
        invoiceType: "数电普票",
      },
      detailFields: [
        { label: "序号", value: "1" },
        { label: "发票代码", value: "144001918531" },
        { label: "发票号码", value: "00853128" },
        { label: "数电发票号码", value: "DZFP-202603-4021" },
        { label: "税收分类编码", value: "3070201010000000000" },
        { label: "特定业务类型", value: "差旅服务" },
        { label: "货物或应税劳务名称", value: "交通及住宿服务" },
        { label: "规格型号", value: "--" },
        { label: "单位", value: "项" },
        { label: "数量", value: "1" },
        { label: "单价", value: "860.00" },
        { label: "发票来源", value: "税局数电" },
        { label: "发票票种", value: "增值税电子普通发票" },
        { label: "发票状态", value: "正常" },
        { label: "是否正数发票", value: "是" },
        { label: "发票风险等级", value: "低" },
        { label: "开票人", value: "张静" },
        { label: "备注", value: "与差旅报销闭环" },
      ],
    },
  ] satisfies WorkbenchRecord[],
};

export const openRecords = {
  oa: [
    {
      id: "OA-202604-003",
      caseId: "CASE-202604-003",
      recordType: "oa",
      label: "付款申请",
      status: "无对应流水（还没付钱）",
      amount: "58,000.00",
      counterparty: "智能工厂设备商",
      actionVariant: "confirm-exception",
      tableValues: {
        applicant: "陈涛",
        projectName: "智能工厂项目",
        applicationType: "供应商付款申请",
        amount: "58,000.00",
        counterparty: "智能工厂设备商",
        reason: "设备尾款待支付",
        reconciliationStatus: "无对应流水（还没付钱）",
      },
      detailFields: [
        { label: "OA单号", value: "OA-202604-003" },
        { label: "审批完成时间", value: "2026-04-02 18:10" },
        { label: "当前流程", value: "待出纳付款" },
        { label: "创建部门", value: "智能制造事业部" },
      ],
    },
    {
      id: "OA-202604-004",
      caseId: "CASE-202604-004",
      recordType: "oa",
      label: "报销单",
      status: "待处理",
      amount: "1,320.00",
      counterparty: "交通出行",
      actionVariant: "confirm-exception",
      tableValues: {
        applicant: "周颖",
        projectName: "项目支持",
        applicationType: "差旅报销",
        amount: "1,320.00",
        counterparty: "交通出行",
        reason: "现场拜访交通费",
        reconciliationStatus: "待处理",
      },
      detailFields: [
        { label: "OA单号", value: "OA-202604-004" },
        { label: "审批完成时间", value: "2026-04-03 09:45" },
        { label: "当前流程", value: "待银行流水确认" },
        { label: "创建部门", value: "客户成功部" },
      ],
    },
  ] satisfies WorkbenchRecord[],
  bank: [
    {
      id: "BNK-202604-201",
      caseId: "CASE-202604-005",
      recordType: "bank",
      label: "收入",
      status: "无对应OA（补贷款）",
      amount: "50,000.00",
      counterparty: "关联公司溯源科技",
      actionVariant: "bank-review",
      tableValues: {
        transactionTime: "2026-04-02 09:18",
        debitAmount: "--",
        creditAmount: "50,000.00",
        counterparty: "关联公司溯源科技",
        paymentAccount: "工商银行 5510",
        invoiceRelationStatus: "无对应OA（补贷款）",
        paymentOrReceiptTime: "2026-04-02 09:18",
        note: "内部往来待补 OA / 借款台账",
        loanRepaymentDate: "2026-05-02",
      },
      detailFields: [
        { label: "账号", value: "6212 **** **** 5510" },
        { label: "账户名称", value: "溯源科技有限公司-工商银行专户" },
        { label: "余额", value: "1,608,204.70" },
        { label: "币种", value: "CNY" },
        { label: "对方账号", value: "6212 **** **** 7721" },
        { label: "对方开户机构", value: "工商银行上海浦东支行" },
        { label: "记账日期", value: "2026-04-02" },
        { label: "摘要", value: "内部资金往来" },
        { label: "备注", value: "需确认补贷款还是内部往来" },
        { label: "账户明细编号-交易流水号", value: "DET-20260402-201" },
        { label: "企业流水号", value: "CORP-20260402-1062" },
        { label: "凭证种类", value: "转账收入" },
        { label: "凭证号", value: "VCH-040209-01" },
      ],
    },
    {
      id: "BNK-202604-202",
      caseId: "CASE-202604-004",
      recordType: "bank",
      label: "支取",
      status: "追票",
      amount: "9,800.00",
      counterparty: "办公耗材商",
      actionVariant: "bank-review",
      tableValues: {
        transactionTime: "2026-04-03 16:48",
        debitAmount: "9,800.00",
        creditAmount: "--",
        counterparty: "办公耗材商",
        paymentAccount: "农业银行 2241",
        invoiceRelationStatus: "追票",
        paymentOrReceiptTime: "2026-04-03 16:48",
        note: "应付已发生，待进项票补齐",
        loanRepaymentDate: "--",
      },
      detailFields: [
        { label: "账号", value: "6228 **** **** 2241" },
        { label: "账户名称", value: "溯源科技有限公司-农业银行结算户" },
        { label: "余额", value: "323,860.11" },
        { label: "币种", value: "CNY" },
        { label: "对方账号", value: "6228 **** **** 6617" },
        { label: "对方开户机构", value: "农业银行杭州滨江支行" },
        { label: "记账日期", value: "2026-04-03" },
        { label: "摘要", value: "办公耗材采购付款" },
        { label: "备注", value: "供应商未开发票，进入追票队列" },
        { label: "账户明细编号-交易流水号", value: "DET-20260403-202" },
        { label: "企业流水号", value: "CORP-20260403-2704" },
        { label: "凭证种类", value: "网银付款" },
        { label: "凭证号", value: "VCH-040316-08" },
      ],
    },
  ] satisfies WorkbenchRecord[],
  invoice: [
    {
      id: "INV-OUT-202604-005",
      caseId: "CASE-202604-003",
      recordType: "invoice",
      label: "销项票",
      status: "待收款",
      amount: "90,000.00",
      counterparty: "智能工厂客户",
      actionVariant: "confirm-exception",
      tableValues: {
        sellerTaxId: "91310000MA1K8A001X",
        sellerName: "溯源科技有限公司",
        buyerTaxId: "91320214MA20Q7712C",
        buyerName: "智能工厂客户",
        issueDate: "2026-04-01",
        amount: "90,000.00",
        taxRate: "13%",
        taxAmount: "11,700.00",
        grossAmount: "101,700.00",
        invoiceType: "数电专票",
      },
      detailFields: [
        { label: "序号", value: "1" },
        { label: "发票代码", value: "032002600224" },
        { label: "发票号码", value: "00071662" },
        { label: "数电发票号码", value: "DZFP-202604-1132" },
        { label: "税收分类编码", value: "3040301000000000000" },
        { label: "特定业务类型", value: "软件实施" },
        { label: "货物或应税劳务名称", value: "项目实施服务" },
        { label: "规格型号", value: "--" },
        { label: "单位", value: "项" },
        { label: "数量", value: "1" },
        { label: "单价", value: "90,000.00" },
        { label: "发票来源", value: "税局数电" },
        { label: "发票票种", value: "增值税电子专用发票" },
        { label: "发票状态", value: "正常" },
        { label: "是否正数发票", value: "是" },
        { label: "发票风险等级", value: "低" },
        { label: "开票人", value: "王青" },
        { label: "备注", value: "待匹配后续收款或预收款处理" },
      ],
    },
    {
      id: "INV-IN-202604-016",
      caseId: "CASE-202604-004",
      recordType: "invoice",
      label: "进项票",
      status: "待付款",
      amount: "9,800.00",
      counterparty: "办公耗材商",
      actionVariant: "confirm-exception",
      tableValues: {
        sellerTaxId: "91330108MA27B4011D",
        sellerName: "办公耗材商",
        buyerTaxId: "91310000MA1K8A001X",
        buyerName: "溯源科技有限公司",
        issueDate: "2026-04-03",
        amount: "9,800.00",
        taxRate: "13%",
        taxAmount: "1,274.00",
        grossAmount: "11,074.00",
        invoiceType: "纸质专票",
      },
      detailFields: [
        { label: "序号", value: "1" },
        { label: "发票代码", value: "3300214130" },
        { label: "发票号码", value: "12561048" },
        { label: "数电发票号码", value: "--" },
        { label: "税收分类编码", value: "1070401010000000000" },
        { label: "特定业务类型", value: "办公采购" },
        { label: "货物或应税劳务名称", value: "办公耗材" },
        { label: "规格型号", value: "批量采购" },
        { label: "单位", value: "批" },
        { label: "数量", value: "1" },
        { label: "单价", value: "9,800.00" },
        { label: "发票来源", value: "纸票扫描导入" },
        { label: "发票票种", value: "增值税专用发票" },
        { label: "发票状态", value: "正常" },
        { label: "是否正数发票", value: "是" },
        { label: "发票风险等级", value: "中" },
        { label: "开票人", value: "孙蓉" },
        { label: "备注", value: "待与办公采购支出流水核销" },
      ],
    },
  ] satisfies WorkbenchRecord[],
};
