from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class ReadModelManifestEntry:
    key: str
    scope_type: str
    refresh_event_type: str
    primary_worker_instance: str
    auxiliary_refresh_worker_instances: tuple[str, ...]
    query_status_contract: str
    projection_strategy: str
    all_scope_semantics: str
    partition_key_contract: str
    scoped_incremental_target: str
    full_rebuild_fallback: str
    freshness_proof_contract: str
    force_refresh_contract: str
    operation_barrier_contract: str
    repository_port_contract: tuple[str, ...]
    query_owner: str
    repository_owner: str
    permission_owner: str
    test_owner: str


READ_MODEL_MANIFEST: dict[str, ReadModelManifestEntry] = {
    "workbench": ReadModelManifestEntry(
        key="workbench",
        scope_type="workbench",
        refresh_event_type="workbench.read_model.refresh",
        primary_worker_instance="workbench",
        auxiliary_refresh_worker_instances=(),
        query_status_contract="equivalent_active_generation",
        projection_strategy="active_generation_scoped_publish",
        all_scope_semantics="active_month_shard_aggregate",
        partition_key_contract="month_scope active generation; all aggregates active month shards",
        scoped_incremental_target="workbench active generation rows, groups, summaries and details for affected month scopes",
        full_rebuild_fallback="gateway force refresh rebuilds requested active month generation or all aggregate from canonical facts",
        freshness_proof_contract="active generation metadata, expected source_versions including matching rules, and current-effective dirty/outbox state",
        force_refresh_contract="gateway_force_refresh_active_generation_scope",
        operation_barrier_contract="app_status_registry_target",
        repository_port_contract=(
            "get_workbench_initial_page",
            "get_workbench_summary",
            "get_workbench_groups_page",
            "get_workbench_group_detail",
            "get_workbench_row_detail",
            "find_workbench_row_scope_key",
            "get_workbench_refresh_status",
            "get_workbench_groups_freshness_status",
            "save_workbench_read_models",
            "load_workbench_read_models",
        ),
        query_owner="WorkbenchQueryFacade",
        repository_owner="PostgresReadModelRepository.workbench",
        permission_owner="workbench_api_session",
        test_owner="tests/test_workbench_sql_runtime.py",
    ),
    "workbench_relation": ReadModelManifestEntry(
        key="workbench_relation",
        scope_type="workbench_relation",
        refresh_event_type="workbench_relation.read_model.refresh",
        primary_worker_instance="workbench-relation",
        auxiliary_refresh_worker_instances=(),
        query_status_contract="self_managed_freshness",
        projection_strategy="scoped_incremental_distribution",
        all_scope_semantics="fan_out_command",
        partition_key_contract="relation month_scope; all is fan-out only",
        scoped_incremental_target="workbench relation distribution rows and groups for affected month scopes",
        full_rebuild_fallback="gateway force refresh fan-out rebuilds relation month shards and marks empty scopes",
        freshness_proof_contract="workbench_relation scope source_versions plus app_status readiness and current-effective dirty/outbox state",
        force_refresh_contract="gateway_force_refresh",
        operation_barrier_contract="app_status_registry_target",
        repository_port_contract=(
            "save_workbench_relation_distribution",
            "mark_workbench_relation_scope_empty",
            "get_workbench_relation_rows_by_ids",
            "list_workbench_relation_rows",
            "get_workbench_relation_groups_by_ids",
            "workbench_relation_source_versions",
            "workbench_relation_scope_summary",
            "count_batch_accounting_relations_by_year",
        ),
        query_owner="WorkbenchRelationReadFacade",
        repository_owner="WorkbenchRelationReadModelRepositoryPort",
        permission_owner="downstream_page_api_session",
        test_owner="tests/test_workbench_relation_read_facade.py",
    ),
    "bank_detail": ReadModelManifestEntry(
        key="bank_detail",
        scope_type="bank_detail",
        refresh_event_type="bank_detail.read_model.refresh",
        primary_worker_instance="bank-detail",
        auxiliary_refresh_worker_instances=(),
        query_status_contract="self_managed_freshness",
        projection_strategy="partitioned_scoped_incremental",
        all_scope_semantics="fan_out_command",
        partition_key_contract="bank transaction month_scope; all is fan-out only",
        scoped_incremental_target="bank detail transaction/tag/account rows for affected month scopes",
        full_rebuild_fallback="gateway force refresh all enumerates available month shards and rebuilds each shard",
        freshness_proof_contract="month shard scope summary/source_versions plus current-effective dirty/outbox state",
        force_refresh_contract="gateway_force_refresh",
        operation_barrier_contract="app_status_registry_target",
        repository_port_contract=(
            "bank_detail_scope_keys_for_range",
            "bank_detail_scope_summary",
            "list_bank_detail_transactions",
            "list_bank_detail_accounts",
            "get_bank_detail_tagged_rows_by_transaction_ids",
            "list_bank_detail_tagged_rows_by_month",
            "save_bank_detail_rows",
            "mark_bank_detail_scope",
        ),
        query_owner="BankDetailsApplicationService",
        repository_owner="BankDetailReadModelRepositoryPort",
        permission_owner="bank_details_api_session",
        test_owner="tests/test_bank_details_sql_runtime.py",
    ),
    "bank_account_balance": ReadModelManifestEntry(
        key="bank_account_balance",
        scope_type="bank_account_balance",
        refresh_event_type="bank_account_balance.read_model.refresh",
        primary_worker_instance="bank-account-balance",
        auxiliary_refresh_worker_instances=(),
        query_status_contract="self_managed_freshness",
        projection_strategy="partitioned_scoped_incremental",
        all_scope_semantics="queryable_all_scope",
        partition_key_contract="global all scope only",
        scoped_incremental_target="bank account balance snapshot for all accounts",
        full_rebuild_fallback="gateway force refresh rebuilds the all-only account balance projection",
        freshness_proof_contract="bank_account_balance:all scope summary plus current-effective dirty/outbox state",
        force_refresh_contract="gateway_force_refresh",
        operation_barrier_contract="app_status_registry_target",
        repository_port_contract=(
            "bank_account_balance_scope_summary",
            "list_bank_account_balances",
            "save_bank_account_balances",
        ),
        query_owner="BankDetailsApplicationService",
        repository_owner="BankAccountBalanceReadModelRepositoryPort",
        permission_owner="bank_details_api_session",
        test_owner="tests/test_bank_account_balance_read_model.py",
    ),
    "pending_invoice": ReadModelManifestEntry(
        key="pending_invoice",
        scope_type="pending_invoice",
        refresh_event_type="pending_invoice.read_model.refresh",
        primary_worker_instance="pending-invoice",
        auxiliary_refresh_worker_instances=("search-pending",),
        query_status_contract="self_managed_freshness",
        projection_strategy="scoped_incremental",
        all_scope_semantics="forbidden_bare_all",
        partition_key_contract="direction:filter_group[:YYYY-MM] page scope",
        scoped_incremental_target="pending invoice rows and filter options for direction/filter/month page scopes",
        full_rebuild_fallback="page-first-screen force refresh rebuilds explicit pending invoice page scopes; bare all remains rejected",
        freshness_proof_contract="pending invoice source summary plus bank_detail and workbench_relation source_versions for requested page scope",
        force_refresh_contract="gateway_force_refresh_with_page_first_screen_scope",
        operation_barrier_contract="app_status_registry_target",
        repository_port_contract=(
            "list_pending_invoice_rows",
            "list_pending_invoice_filter_options",
            "save_pending_invoice_rows",
            "mark_pending_invoice_scope",
            "pending_invoice_source_summary",
            "pending_invoice_bank_detail_source_versions",
            "pending_invoice_workbench_relation_source_versions",
        ),
        query_owner="PendingInvoiceReadModelService",
        repository_owner="PendingInvoiceReadModelRepositoryPort",
        permission_owner="pending_invoices_api_session",
        test_owner="tests/test_pending_invoice_service.py",
    ),
    "search": ReadModelManifestEntry(
        key="search",
        scope_type="search",
        refresh_event_type="search.read_model.refresh",
        primary_worker_instance="search",
        auxiliary_refresh_worker_instances=("search-pending", "search-secondary", "search-tertiary"),
        query_status_contract="self_managed_freshness",
        projection_strategy="partitioned_scoped_index",
        all_scope_semantics="fan_out_command",
        partition_key_contract="search source month_scope; all is fan-out only",
        scoped_incremental_target="search index rows for affected month scopes",
        full_rebuild_fallback="gateway force refresh all enumerates search month shards through the search refresh producer",
        freshness_proof_contract="search index source_versions plus current-effective dirty/outbox state",
        force_refresh_contract="gateway_force_refresh",
        operation_barrier_contract="app_status_registry_target",
        repository_port_contract=(
            "search_index",
            "save_search_index_rows",
        ),
        query_owner="Search read API",
        repository_owner="SearchReadModelRepositoryPort",
        permission_owner="search_api_session",
        test_owner="tests/test_search_pending_sql_runtime.py",
    ),
    "invoice_lifecycle": ReadModelManifestEntry(
        key="invoice_lifecycle",
        scope_type="invoice_lifecycle",
        refresh_event_type="invoice_lifecycle.read_model.refresh",
        primary_worker_instance="invoice-lifecycle",
        auxiliary_refresh_worker_instances=("invoice-lifecycle-secondary",),
        query_status_contract="self_managed_freshness",
        projection_strategy="scoped_incremental",
        all_scope_semantics="fan_out_command",
        partition_key_contract="invoice lifecycle month_scope; all is fan-out only",
        scoped_incremental_target="invoice lifecycle rows for affected invoice subject month scopes",
        full_rebuild_fallback="gateway force refresh all enumerates invoice lifecycle month shards",
        freshness_proof_contract="invoice lifecycle scope source_versions plus current-effective dirty/outbox state",
        force_refresh_contract="gateway_force_refresh",
        operation_barrier_contract="app_status_registry_target",
        repository_port_contract=(
            "save_invoice_lifecycle_rows",
            "mark_invoice_lifecycle_scope",
            "get_invoice_lifecycle_rows_by_subject_ids",
            "get_invoice_lifecycle_rows_by_identity_keys",
            "list_invoice_lifecycle_rows",
            "invoice_lifecycle_scope_summary",
        ),
        query_owner="InvoiceLifecycleReadFacade",
        repository_owner="InvoiceLifecycleReadModelRepositoryPort",
        permission_owner="invoice_lifecycle_page_api_session",
        test_owner="tests/test_invoice_lifecycle_read_model_refresh.py",
    ),
    "input_invoice_usage": ReadModelManifestEntry(
        key="input_invoice_usage",
        scope_type="input_invoice_usage",
        refresh_event_type="input_invoice_usage.read_model.refresh",
        primary_worker_instance="invoice-usage-collection",
        auxiliary_refresh_worker_instances=(),
        query_status_contract="self_managed_freshness",
        projection_strategy="scoped_incremental",
        all_scope_semantics="fan_out_command",
        partition_key_contract="input invoice usage month_scope; all is fan-out only",
        scoped_incremental_target="input invoice usage rows and relation detail rows for affected month scopes",
        full_rebuild_fallback="gateway force refresh all fans out to current input invoice usage month shards and prunes obsolete shards",
        freshness_proof_contract="month shard source_versions including workbench_relation versions plus current-effective dirty/outbox state",
        force_refresh_contract="gateway_force_refresh",
        operation_barrier_contract="app_status_registry_target",
        repository_port_contract=(
            "list_input_invoice_usage_rows",
            "save_input_invoice_usage_rows",
            "mark_input_invoice_usage_scope",
            "prune_input_invoice_usage_scope_shards",
            "get_input_invoice_usage_row_by_row_id",
        ),
        query_owner="InputInvoiceUsageReadModelService",
        repository_owner="InputInvoiceUsageReadModelRepositoryPort",
        permission_owner="input_invoice_usage_api_session",
        test_owner="tests/test_input_invoice_usage_api.py",
    ),
    "output_invoice_collection": ReadModelManifestEntry(
        key="output_invoice_collection",
        scope_type="output_invoice_collection",
        refresh_event_type="output_invoice_collection.read_model.refresh",
        primary_worker_instance="invoice-usage-collection",
        auxiliary_refresh_worker_instances=(),
        query_status_contract="self_managed_freshness",
        projection_strategy="scoped_incremental",
        all_scope_semantics="fan_out_command",
        partition_key_contract="output invoice collection month_scope; all is fan-out only",
        scoped_incremental_target="output invoice collection rows, relation detail rows and lifecycle overlay data for affected month scopes",
        full_rebuild_fallback="gateway force refresh all fans out to current output collection month shards and prunes obsolete shards",
        freshness_proof_contract="month shard source_versions including workbench_relation, lifecycle and receipt versions plus current-effective dirty/outbox state",
        force_refresh_contract="gateway_force_refresh",
        operation_barrier_contract="app_status_registry_target",
        repository_port_contract=(
            "list_output_invoice_collection_rows",
            "get_output_invoice_collection_row_by_row_id",
            "save_output_invoice_collection_rows",
            "mark_output_invoice_collection_scope",
            "prune_output_invoice_collection_scope_shards",
        ),
        query_owner="OutputInvoiceCollectionReadApplicationService",
        repository_owner="OutputInvoiceCollectionReadModelRepositoryPort",
        permission_owner="output_invoice_collection_api_session",
        test_owner="tests/test_output_invoice_collection_api.py",
    ),
    "oa_pending_payment": ReadModelManifestEntry(
        key="oa_pending_payment",
        scope_type="oa_pending_payment",
        refresh_event_type="oa_pending_payment.read_model.refresh",
        primary_worker_instance="oa-pending-payment",
        auxiliary_refresh_worker_instances=(),
        query_status_contract="self_managed_freshness",
        projection_strategy="scoped_incremental",
        all_scope_semantics="fan_out_command",
        partition_key_contract="OA pending payment month_scope; all is fan-out only",
        scoped_incremental_target="OA pending payment rows and relation detail rows for affected month scopes",
        full_rebuild_fallback="gateway force refresh all fans out to current OA pending payment month shards and prunes obsolete shards",
        freshness_proof_contract="month shard source_versions including OA source snapshot/admission/payment, workbench_relation and event source versions plus current-effective dirty/outbox state",
        force_refresh_contract="gateway_force_refresh",
        operation_barrier_contract="app_status_registry_target",
        repository_port_contract=(
            "list_oa_pending_payment_rows",
            "save_oa_pending_payment_rows",
            "mark_oa_pending_payment_scope",
            "prune_oa_pending_payment_scope_shards",
            "get_oa_pending_payment_row_by_row_id",
            "get_oa_pending_payment_row_by_oa_id",
            "get_oa_pending_payment_row_by_bank_transaction_id",
            "get_oa_pending_payment_row_by_invoice_id",
        ),
        query_owner="OaPendingPaymentReadModelService",
        repository_owner="OaPendingPaymentReadModelRepositoryPort",
        permission_owner="oa_pending_payment_api_session",
        test_owner="tests/test_oa_pending_payment_api.py",
    ),
    "cost_statistics": ReadModelManifestEntry(
        key="cost_statistics",
        scope_type="cost_statistics",
        refresh_event_type="cost_statistics.read_model.refresh",
        primary_worker_instance="cost-statistics",
        auxiliary_refresh_worker_instances=(),
        query_status_contract="read_model_query_gateway",
        projection_strategy="partitioned_scoped_parent_rollup",
        all_scope_semantics="queryable_parent_aggregate",
        partition_key_contract="cost statistics active/all month scope plus queryable parent aggregate scope",
        scoped_incremental_target="cost statistics month shards and parent rollup summaries",
        full_rebuild_fallback="gateway force refresh normalizes legacy all/month scopes into active/all month shards and parent rollup rebuild",
        freshness_proof_contract="ReadModelQueryGateway expected schema/source_versions plus app_status readiness for shard and parent scopes",
        force_refresh_contract="gateway_force_refresh",
        operation_barrier_contract="app_status_registry_target",
        repository_port_contract=(
            "get_cost_statistics_scope_metadata",
            "get_cost_statistics_freshness_gate",
            "get_cost_statistics_page",
            "get_cost_statistics_export_page",
            "get_cost_statistics_transaction",
            "active_workbench_source_versions",
            "publish_cost_statistics_read_models",
        ),
        query_owner="CostStatisticsQueryService",
        repository_owner="CostStatisticsReadModelRepositoryPort",
        permission_owner="cost_statistics_api_session",
        test_owner="tests/test_cost_statistics_sql_runtime.py",
    ),
    "tax_offset": ReadModelManifestEntry(
        key="tax_offset",
        scope_type="tax_offset",
        refresh_event_type="tax_offset.read_model.refresh",
        primary_worker_instance="tax-offset",
        auxiliary_refresh_worker_instances=("cost-tax",),
        query_status_contract="read_model_query_gateway",
        projection_strategy="partitioned_scoped_incremental",
        all_scope_semantics="fan_out_command",
        partition_key_contract="tax offset invoice month_scope; all is fan-out only",
        scoped_incremental_target="tax offset rows and summary payload for affected month scopes",
        full_rebuild_fallback="gateway force refresh all enumerates tax offset month shards",
        freshness_proof_contract="ReadModelQueryGateway expected schema/source_versions plus current-effective dirty/outbox state",
        force_refresh_contract="gateway_force_refresh",
        operation_barrier_contract="app_status_registry_target",
        repository_port_contract=(
            "load_tax_offset_read_models",
            "get_tax_offset_view",
            "save_tax_offset_read_models",
        ),
        query_owner="TaxOffsetQueryService",
        repository_owner="TaxOffsetReadModelRepositoryPort",
        permission_owner="tax_offset_api_session",
        test_owner="tests/test_tax_offset_sql_runtime.py",
    ),
    "no_oa_bank_batch": ReadModelManifestEntry(
        key="no_oa_bank_batch",
        scope_type="no_oa_bank_batch",
        refresh_event_type="no_oa_bank_batch.read_model.refresh",
        primary_worker_instance="no-oa-bank-batch",
        auxiliary_refresh_worker_instances=(),
        query_status_contract="self_managed_freshness",
        projection_strategy="scoped_incremental",
        all_scope_semantics="fan_out_command",
        partition_key_contract="no-OA bank batch month_scope; all is fan-out only",
        scoped_incremental_target="no-OA bank batch public rows for affected month scopes",
        full_rebuild_fallback="gateway force refresh all enumerates no-OA month shards through the refresh producer",
        freshness_proof_contract="no-OA source_versions plus app_status readiness and current-effective dirty/outbox state",
        force_refresh_contract="gateway_force_refresh",
        operation_barrier_contract="app_status_registry_target",
        repository_port_contract=(
            "list_no_oa_bank_batch_rows",
            "no_oa_bank_batch_source_versions_summary",
        ),
        query_owner="NoOaBankBatchApplicationService",
        repository_owner="NoOaBankBatchReadModelRepositoryPort",
        permission_owner="no_oa_bank_batch_api_session",
        test_owner="tests/test_no_oa_bank_batch_application_service.py",
    ),
    "bank_flow_rule_batch": ReadModelManifestEntry(
        key="bank_flow_rule_batch",
        scope_type="bank_flow_rule_batch",
        refresh_event_type="bank_flow_rule_batch.read_model.refresh",
        primary_worker_instance="bank-flow-rule-batch",
        auxiliary_refresh_worker_instances=(),
        query_status_contract="self_managed_freshness",
        projection_strategy="scoped_incremental",
        all_scope_semantics="fan_out_command",
        partition_key_contract="bank-flow rule batch month_scope; all is fan-out only",
        scoped_incremental_target="bank-flow rule batch public rows for affected month scopes",
        full_rebuild_fallback="gateway force refresh all enumerates bank-flow rule batch month shards through the refresh producer",
        freshness_proof_contract="bank_flow_rule_batch source_versions plus app_status readiness and current-effective dirty/outbox state",
        force_refresh_contract="gateway_force_refresh",
        operation_barrier_contract="app_status_registry_target",
        repository_port_contract=(
            "list_bank_flow_rule_batch_rows",
            "bank_flow_rule_batch_source_versions_summary",
        ),
        query_owner="BankFlowRuleBatchApplicationService",
        repository_owner="BankFlowRuleBatchReadModelRepositoryPort",
        permission_owner="bank_flow_rule_batch_api_session",
        test_owner="tests/test_bank_flow_rule_batch_backend_boundary.py",
    ),
    "turnover_ledger": ReadModelManifestEntry(
        key="turnover_ledger",
        scope_type="turnover_ledger",
        refresh_event_type="turnover_ledger.read_model.refresh",
        primary_worker_instance="turnover-ledger",
        auxiliary_refresh_worker_instances=(),
        query_status_contract="read_model_query_gateway",
        projection_strategy="partitioned_scoped_incremental",
        all_scope_semantics="fan_out_command",
        partition_key_contract="turnover ledger month_scope; all is fan-out only",
        scoped_incremental_target="turnover ledger grouped/list rows for affected month scopes",
        full_rebuild_fallback="gateway force refresh all enumerates turnover ledger month shards and supports explicit clear/rebuild",
        freshness_proof_contract="ReadModelQueryGateway expected schema/source_versions plus workbench_relation versions and current-effective dirty/outbox state",
        force_refresh_contract="gateway_force_refresh",
        operation_barrier_contract="app_status_registry_target",
        repository_port_contract=(
            "list_turnover_ledger_view",
            "save_turnover_ledger_rows",
            "clear_turnover_ledger_rows",
        ),
        query_owner="TurnoverLedgerQueryService",
        repository_owner="TurnoverLedgerReadModelRepositoryPort",
        permission_owner="turnover_ledger_api_session",
        test_owner="tests/test_turnover_ledger_query_service.py",
    ),
}


def read_model_manifest_by_scope_type() -> dict[str, ReadModelManifestEntry]:
    return {entry.scope_type: entry for entry in READ_MODEL_MANIFEST.values()}


def read_model_manifest_by_refresh_event_type() -> dict[str, ReadModelManifestEntry]:
    return {entry.refresh_event_type: entry for entry in READ_MODEL_MANIFEST.values()}


def is_command_only_read_model_scope(read_model_key: str, scope_key: str) -> bool:
    """Return whether a scope is a fan-out command rather than queryable state."""

    entry = READ_MODEL_MANIFEST.get(str(read_model_key or "").strip())
    normalized_scope_key = str(scope_key or "").strip()
    if entry is None or not normalized_scope_key:
        return False
    is_all_scope = normalized_scope_key == "all" or normalized_scope_key.endswith(":all")
    return is_all_scope and entry.all_scope_semantics == "fan_out_command"
