from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class ApplicationStateStoreProtocol(Protocol):
    @property
    def data_dir(self) -> Path: ...

    @property
    def storage_backend(self) -> str: ...

    @property
    def storage_mode(self) -> str: ...

    @property
    def mongo_database_name(self) -> str | None: ...

    def load(self) -> dict[str, Any]: ...

    def save(self, payload: dict[str, Any]) -> None: ...

    def load_app_settings(self) -> dict[str, Any]: ...

    def save_app_settings(self, payload: dict[str, Any]) -> None: ...

    def load_pending_invoice_commands(self) -> dict[str, Any]: ...

    def save_pending_invoice_commands(self, snapshot: dict[str, Any]) -> None: ...

    def load_oa_attachment_invoice_cache_entry(self, cache_key: str) -> dict[str, object] | None: ...

    def save_oa_attachment_invoice_cache_entry(self, cache_key: str, payload: dict[str, object]) -> None: ...

    def clear_oa_attachment_invoice_cache(self) -> int: ...

    def load_oa_sync_state(self) -> dict[str, Any]: ...

    def save_oa_sync_state(self, snapshot: dict[str, Any]) -> None: ...

    def load_manual_oa_imports(self) -> dict[str, object]: ...

    def save_manual_oa_imports(self, payload: dict[str, object]) -> None: ...

    def add_manual_oa_imports(
        self,
        row_ids: list[str],
        *,
        actor_id: str | None = None,
        audit: dict[str, object] | None = None,
    ) -> dict[str, object]: ...

    def remove_manual_oa_import(self, row_id: str, *, actor_id: str | None = None) -> bool: ...

    def store_import_file(self, *, session_id: str, file_id: str, file_name: str, content: bytes) -> str: ...

    def read_import_file(self, stored_file_path: str) -> bytes: ...

    def delete_import_files(self, stored_file_paths: list[str]) -> int: ...

    def store_etc_import_archive(
        self,
        *,
        session_id: str,
        file_id: str,
        file_name: str,
        content: bytes,
    ) -> dict[str, object]: ...

    def read_etc_import_archive(self, stored_file_path: str) -> bytes: ...

    def delete_etc_import_archives(self, stored_file_paths: list[str]) -> int: ...

    def import_session_exists(self, session_id: str) -> bool: ...

    def import_file_exists(self, file_id: str) -> bool: ...

    def import_batch_exists(self, batch_id: str) -> bool: ...

    def invoice_exists(self, invoice_id: str) -> bool: ...

    def transaction_exists(self, transaction_id: str) -> bool: ...

    def load_workbench_pair_relations(self) -> dict[str, Any]: ...

    def save_workbench_pair_relations(self, snapshot: dict[str, Any], *, changed_case_ids: set[str] | None = None) -> None: ...

    def load_workbench_overrides(self) -> dict[str, Any]: ...

    def load_no_oa_bank_batches(self) -> dict[str, Any]: ...

    def save_no_oa_bank_batches(self, snapshot: dict[str, Any], *, relation_mode: str = "no_oa_bank_batch") -> None: ...

    def save_no_oa_bank_batches_scope(
        self,
        snapshot: dict[str, Any],
        *,
        scope_key: str,
        relation_mode: str = "no_oa_bank_batch",
    ) -> None: ...
    def load_bank_flow_rule_batches(self) -> dict[str, Any]: ...
    def save_bank_flow_rule_batches(self, snapshot: dict[str, Any]) -> None: ...
    def save_bank_flow_rule_batches_scope(
        self,
        snapshot: dict[str, Any],
        *,
        scope_key: str,
    ) -> None: ...
    def save_bank_flow_rule_batch_mutation(
        self,
        *,
        pair_relation_snapshot: dict[str, Any],
        bank_flow_rule_batch_snapshot: dict[str, Any],
        changed_case_ids: set[str] | list[str] | tuple[str, ...],
        changed_scope_keys: set[str] | list[str] | tuple[str, ...],
    ) -> None: ...

    def load_workbench_read_models(self) -> dict[str, Any]: ...

    def save_workbench_read_models(self, snapshot: dict[str, Any], *, changed_scope_keys: set[str] | None = None) -> None: ...

    def load_workbench_candidate_matches(self) -> dict[str, Any]: ...

    def save_workbench_candidate_matches(self, snapshot: dict[str, Any], *, changed_scope_months: set[str] | None = None) -> None: ...

    def save_workbench_matching_dirty_scopes(self, snapshot: dict[str, Any]) -> None: ...

    def load_bank_transaction_categories(self) -> dict[str, Any]: ...

    def save_bank_transaction_categories(self, snapshot: dict[str, Any]) -> None: ...

    def load_turnover_relations(self) -> dict[str, Any]: ...

    def save_turnover_relations(self, snapshot: dict[str, Any]) -> None: ...

    def load_turnover_relation_audit_log(self) -> list[Any]: ...

    def save_turnover_relation_audit_log(self, snapshot: list[Any]) -> None: ...

    def load_turnover_ledger_extras(self) -> dict[str, Any]: ...

    def save_turnover_ledger_extras(self, snapshot: dict[str, Any]) -> None: ...

    def load_cost_statistics_read_models(self) -> dict[str, Any]: ...

    def save_cost_statistics_read_models(self, snapshot: dict[str, Any], *, changed_scope_keys: set[str] | None = None) -> None: ...

    def load_tax_offset_read_models(self) -> dict[str, Any]: ...

    def save_tax_offset_read_models(self, snapshot: dict[str, Any], *, changed_scope_keys: set[str] | None = None) -> None: ...

    def load_tax_certified_imports(self) -> dict[str, Any]: ...

    def save_tax_certified_imports(self, snapshot: dict[str, Any]) -> None: ...

    def load_etc_state(self) -> dict[str, Any]: ...

    def save_etc_state(self, snapshot: dict[str, Any]) -> None: ...

    def load_etc_reconciliation_state(self) -> dict[str, Any]: ...

    def save_etc_reconciliation_state(self, snapshot: dict[str, Any]) -> None: ...

    def store_etc_reconciliation_file(self, *, task_id: str, file_id: str, file_name: str, content: bytes) -> str: ...

    def read_etc_reconciliation_file(self, stored_file_path: str) -> bytes: ...

    def store_etc_invoice_file(self, *, invoice_number: str, file_name: str, content: bytes) -> str: ...

    def read_etc_invoice_file(self, stored_file_path: str) -> bytes: ...

    def etc_invoice_file_exists(self, stored_file_path: str) -> bool: ...

    def delete_etc_invoice_file(self, stored_file_path: str) -> None: ...

    def load_background_jobs(self) -> dict[str, Any]: ...

    def save_background_jobs(self, snapshot: dict[str, Any]) -> None: ...

    def load_app_health_alerts(self) -> dict[str, Any]: ...

    def save_app_health_alerts(self, snapshot: dict[str, Any]) -> None: ...

    def save_workbench_overrides(
        self,
        workbench_overrides_snapshot: dict[str, Any],
        *,
        changed_row_ids: set[str] | None = None,
    ) -> None: ...

    def save_workbench_exception_cases(self, snapshot: dict[str, Any]) -> None: ...

    def save_historical_etc_repair_bundle(
        self,
        *,
        bundle_id: str,
        file_name: str,
        content: bytes,
        metadata: dict[str, Any] | None = None,
    ) -> dict[str, Any]: ...

    def load_historical_etc_repair_bundle_metadata(self) -> dict[str, dict[str, Any]]: ...

    def read_historical_etc_repair_bundle(self, bundle_id: str) -> dict[str, Any] | None: ...

    def save_historical_etc_repair_parsed_seed(
        self,
        *,
        bundle_id: str,
        parsed_seed: dict[str, Any],
    ) -> dict[str, Any]: ...

    def load_historical_etc_repair_parsed_seeds(self) -> dict[str, dict[str, Any]]: ...

    def load_historical_etc_repair_parsed_seed(self, bundle_id: str) -> dict[str, Any] | None: ...

    def load_historical_etc_repair_states(self) -> dict[str, dict[str, Any]]: ...

    def save_historical_etc_repair_states(self, states: dict[str, Any]) -> None: ...
