import { expect, test } from './fixtures/strictTest';
import { expectNoUnexpectedSuccessUiErrors } from './fixtures/successAssertions';

const enabled = process.env.FIN_OPS_E2E_PRODUCTION_SMOKE === '1';
const token = process.env.FIN_OPS_E2E_ADMIN_TOKEN;
const rulesPath = '/fin-ops-api/api/input-invoice-usage/payment-status-rules';
test.use({ screenshot: 'off', trace: 'off', video: 'off' });

test('production rules grid preserves configuration while editing and restoring drafts', async ({ page }, info) => {
  test.skip(!enabled || !token, 'Requires explicit production read-only verification and local token.');
  test.setTimeout(120_000);
  await page.context().addCookies([{ name: 'Admin-Token', value: token!, domain: 'www.yn-sourcing.com', path: '/', secure: true, sameSite: 'Lax' }]);
  const errors: string[] = [];
  const writes: string[] = [];
  const ruleRequests: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.route('**/*', async route => {
    const request = route.request();
    if (!['GET', 'HEAD', 'OPTIONS'].includes(request.method())) {
      writes.push(`${request.method()} ${new URL(request.url()).pathname}`);
      await route.abort('blockedbyclient');
      return;
    }
    if (new URL(request.url()).pathname === rulesPath) ruleRequests.push(request.method());
    await route.continue();
  });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.goto('/fin-ops/input-invoice-usage');
  await expect(page.getByRole('region', { name: '进项发票使用分类' })).toHaveAttribute('aria-busy', 'false');
  const rulesResponse = page.waitForResponse(response => new URL(response.url()).pathname === rulesPath);
  if (await page.getByRole('button', { name: '更多页面操作' }).isVisible()) await page.getByRole('button', { name: '更多页面操作' }).click();
  const start = Date.now();
  await page.getByRole('button', { name: '发票与支付状态规则设置' }).click();
  const beforeResponse = await rulesResponse;
  expect(beforeResponse.status()).toBe(200);
  const before = await beforeResponse.json();
  const drawer = page.getByRole('dialog', { name: '发票与支付状态规则设置' });
  await expect(drawer.getByRole('grid', { name: '支付状态规则' })).toBeVisible();
  const openMs = Date.now() - start;
  expect(before.rules.length).toBeGreaterThan(1);
  await expect(drawer.getByRole('columnheader')).toHaveText(['启用', '顺序', '规则', 'OA 申请人', '流水', '发票与付款比较', '发票净额', '完全匹配', '发票/OA 金额匹配', '操作']);
  const geometry: Record<string, unknown>[] = [];
  for (const width of [1920, 1440, 1024]) {
    await page.setViewportSize({ width, height: 1080 });
    const row = await drawer.getByRole('row').nth(1).boundingBox();
    expect(row!.height).toBeGreaterThanOrEqual(44);
    expect(row!.height).toBeLessThanOrEqual(50);
    expect(await drawer.evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true);
    await expect(drawer.getByRole('button', { name: '保存', exact: true })).toBeVisible();
    geometry.push({ width, rowHeight: row!.height });
    await page.screenshot({ path: info.outputPath(`production-rules-grid-${width}.png`), animations: 'disabled' });
  }
  await page.setViewportSize({ width: 1920, height: 1080 });
  const row = drawer.getByRole('row').nth(1);
  const editStart = Date.now();
  await row.getByRole('button', { name: / 流水条件$/ }).click();
  await page.getByRole('option', { name: '✓', exact: true }).click();
  await row.getByRole('button', { name: / 金额比较条件$/ }).click();
  await expect(page.getByRole('option')).toHaveText(['不限', '＝', '＜', '≤', '＞', '≥']);
  await page.getByRole('option', { name: '≥', exact: true }).click();
  await row.getByRole('button', { name: / 发票净额条件$/ }).click();
  await expect(page.getByRole('option')).toHaveText(['不限', '＜0', '≤0', '＝0', '≥0', '＞0']);
  await page.getByRole('option', { name: '≥0', exact: true }).click();
  await row.getByRole('button', { name: / 金额比较条件$/ }).click();
  await page.getByRole('option', { name: '≤', exact: true }).click();
  await row.getByRole('button', { name: / 流水条件$/ }).click();
  await page.getByRole('option', { name: '✕', exact: true }).click();
  await expect(row.getByLabel(/ 金额比较不可用$/)).toHaveText('—');
  await row.getByRole('combobox').click();
  await page.getByRole('option', { name: '指定申请人', exact: true }).click();
  await expect(page.getByRole('listbox', { name: 'OA 申请人账号' })).toBeVisible();
  await page.screenshot({ path: info.outputPath('production-rules-applicants.png'), animations: 'disabled' });
  await page.keyboard.press('Escape');
  await expect(row.getByRole('combobox')).toHaveAttribute('aria-expanded', 'false');
  await expect(drawer).toBeVisible();
  await row.getByRole('combobox').click();
  await page.getByRole('option', { name: '无 OA', exact: true }).click();
  await expect(row.getByLabel(/ OA 金额匹配不可用$/)).toHaveText('—');
  await drawer.getByRole('button', { name: '还原', exact: true }).click();
  const labels = await drawer.getByRole('textbox').evaluateAll(nodes => nodes.map(node => (node as HTMLInputElement).value));
  await row.getByRole('button', { name: /^下移规则 / }).click();
  await expect(drawer.getByRole('textbox', { name: '标签 1' })).toHaveValue(labels[1]);
  await drawer.getByRole('button', { name: '还原', exact: true }).click();
  expect(await drawer.getByRole('textbox').evaluateAll(nodes => nodes.map(node => (node as HTMLInputElement).value))).toEqual(labels);
  await expect(drawer.getByRole('button', { name: '保存', exact: true })).toBeDisabled();
  const editMs = Date.now() - editStart;
  expect(ruleRequests).toEqual(['GET']);
  const reloaded = page.waitForResponse(response => new URL(response.url()).pathname === rulesPath);
  await drawer.getByRole('button', { name: '重新加载', exact: true }).click();
  const after = await (await reloaded).json();
  expect(after.rules).toEqual(before.rules);
  expect(after.version).toEqual(before.version);
  await expect(drawer.getByRole('grid', { name: '支付状态规则' })).toBeVisible();
  await drawer.getByRole('button', { name: '关闭支付状态规则抽屉' }).click();
  expect(errors).toEqual([]);
  expect(writes).toEqual([]);
  await expectNoUnexpectedSuccessUiErrors(page);
  await info.attach('production-rules-grid-readonly', { body: JSON.stringify({ version: before.version, ruleCount: before.rules.length, applicantCount: before.applicantOptions.length, openMs, editMs, geometry, ruleRequests, writes, errors }), contentType: 'application/json' });
});
