server_name: finops-nats
listen: 0.0.0.0:4222
http: 0.0.0.0:8222

jetstream {
  store_dir: /data/jetstream
  max_mem_store: 512Mb
  max_file_store: 20Gb
}

authorization {
  users: [
    {
      user: $NATS_FINOPS_PUBLISHER_USER
      password: $NATS_FINOPS_PUBLISHER_PASSWORD
      permissions: {
        publish: ["finops.events.>", "finops.jobs.>", "finops.dlq.>"]
        subscribe: ["_INBOX.>"]
      }
    },
    {
      user: $NATS_FINOPS_WORKER_USER
      password: $NATS_FINOPS_WORKER_PASSWORD
      permissions: {
        publish: ["finops.dlq.>", "_INBOX.>"]
        subscribe: ["finops.jobs.>", "finops.events.>", "$JS.API.CONSUMER.>", "$JS.ACK.>"]
      }
    },
    {
      user: $NATS_FINOPS_OPS_USER
      password: $NATS_FINOPS_OPS_PASSWORD
      permissions: {
        publish: [">"]
        subscribe: [">"]
      }
    }
  ]
}
